name: server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Init Jiff
        run: git submodule init jiff
      - name: Update
        run: git submodule update
      - name: Install
        run: npm ci
      - name: Move into JIff dir
        run: cd jiff && npm ci
      - name: Verify Docker Image
        uses: docker/build-push-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Build
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: multiparty/web-mpc:latest
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true
